Repository devs-in-tech/DevsInTech, pull requests merged in 2023-07, with the labels that each got.

#301 feat: (frontend)Added preloader page using hashloader issue-133
  package.json
  pnpm-lock.yaml
  src/pages/home/index.jsx
Labels: enhancement, gssoc23, level2

#317 dependabot.yml file is added
  .github/dependabot.yml
Labels: enhancement, gssoc23, level1

#197 [fix] Add a checkbox for GSSoC contributors
  .github/ISSUE_TEMPLATE/bug.yml
  .github/ISSUE_TEMPLATE/docs.yml
  .github/ISSUE_TEMPLATE/feature-request.yml
  .github/ISSUE_TEMPLATE/style.yml
Labels: gssoc23, under review, level2

#327 Fixing Import of testimonial.js
  src/components/testimonial.js
  src/pages/home/index.jsx
Labels: bug, gssoc23, level1

#309 Redesign stats section
  src/components/HomePage/stats/index.jsx
Labels: enhancement, gssoc23, level2

#316 Custom Error Page added
  src/pages/404.js
Labels: enhancement, gssoc23, level3

#331 feat: hover effect were added scope:frontend description : Hover ef…
  src/components/Navbar.jsx
Labels: enhancement, gssoc23, level2

#325 auto-comment.yml is added
  .github/workflows/auto-comment.yml
Labels: documentation, gssoc23, level1

#340 feat: implement contributors page
  package.json
  pnpm-lock.yaml
  src/components/Navbar.jsx
  src/pages/Contributors.js
Labels: enhancement, gssoc23, level3

#348 docs: website link added in readme
  README.md
Labels: documentation, gssoc23, level1

#330 Events slider
  src/components/HeaderSocialMedia.jsx
  src/components/HomePage/Events_Cards/index.jsx
  src/components/HomePage/stats/index.jsx
  src/components/Navbar.jsx
Labels: enhancement, gssoc23, level2

#347 feat: implement responsiveness for contributors page
  src/pages/Contributors.js
Labels: bug, gssoc23, under review, level2

#355 Stat responsiveness
  src/components/HomePage/stats/index.jsx
Labels: bug, gssoc23, level1

#367 Added Newsletter Subscription to DevsInTech Website
  public/check-markf.png
  src/components/Footer.jsx
  src/components/Letter.jsx
  src/components/Navbar.jsx
  src/pages/api/subscribes.js
  src/pages/home/index.jsx
Labels: enhancement, gssoc23, level3
