Repository devs-in-tech/DevsInTech, pull requests merged in 2023-06, with the labels that each got.

#204 Changed the footer text from "Lorem ipsum ..." to appropriate text.
  src/components/Footer.jsx
Labels: GSSoC23, Level 1

#211 Closes #202 - Go To Top Button Covers Link in Footer
  src/components/ScrollToTop.jsx
Labels: GSSoC23, under review, Level 1

#215 feat: team page layout added
  src/assets/Team/Developer.jpg
  src/components/Navbar.jsx
  src/components/TeamPage/index.jsx
  src/components/content/team.js
  src/pages/team/index.jsx
Labels: enhancement, GSSoC23, Level 3

#31 feat: Add testimonial carousel
  src/components/testimonial.js
  src/pages/home/index.jsx
Labels: enhancement, GSSoC23, Level 3

#187 feat: Social Media Icons on header GsSoC'23
  public/discord.svg
  public/github.svg
  public/linkedin.svg
  public/twitter.svg
  src/components/HeaderSocialMedia.jsx
  src/components/Navbar.jsx
  src/components/iconbutton/index.js
Labels: gssoc23, under review, level2

#268 Added the dockerfile for containerizing the app
  .dockerignore
  Dockerfile
Labels: enhancement, gssoc23, level3

#238 [style]: Improved styles for hover on social media icons in the footer section.
  src/components/Footer.jsx
Labels: enhancement, gssoc23, under review, level2

#276 feat: add codeql workflow
  .github/workflows/codeql.yml
Labels: documentation, gssoc23, level1

#281 Update data in the events sections
  src/components/content/events.js
Labels: enhancement, gssoc23, level1

#283 Updated Testimonial Section in Testimonial.js File
  public/boy.png
  public/girl.jpg
  src/components/testimonial.js
Labels: enhancement, gssoc23, level2

#229 Hover button, font size improvement
  src/components/FaqAccordion.jsx
  src/components/FaqAccordionItem.jsx
  src/components/Footer.jsx
  src/components/Hello.js
  src/components/HeroSection/index.jsx
  src/components/HomePage/Events_Cards/card.jsx
  src/components/HomePage/Events_Cards/index.jsx
  src/components/HomePage/Introductionvideo.jsx
  src/components/HomePage/aboutCommunity/index.jsx
  src/components/HomePage/index.js
  src/components/HomePage/stats/index.jsx
  src/components/Navbar.jsx
  src/components/ScrollToTop.jsx
  src/components/button/index.js
  src/components/content/events.js
  src/components/content/faq.js
  src/components/header/index.js
  src/components/index.js
  src/pages/_app.js
  src/pages/_document.js
  src/pages/about/index.js
  src/pages/api/hello.js
  src/pages/events/index.jsx
  src/pages/home/index.jsx
  src/pages/index.js
  src/styles/globals.css
  src/utils/helper/validation.js
Labels: enhancement, gssoc23, under review, level2

#291 Created GitHub Action for Code Formatting ⚡
  .github/workflows/lint.yml
Labels: gssoc23, level1

#292 Added Scroll to top button on the team and events page
  src/pages/events/index.jsx
  src/pages/team/index.jsx
Labels: enhancement, gssoc23, level2

#297 Redesigned Events Page and added subpages
  .vscode/settings.json
  public/about.png
  public/blog.jpg
  public/coffee.jpg
  public/quiz.jpg
  public/spaces.jpg
  public/tech-events.jpg
  src/pages/events/blogathon/index.jsx
  src/pages/events/coffee/index.jsx
  src/pages/events/index.jsx
  src/pages/events/quiz/index.jsx
  src/pages/events/spaces/index.jsx
  src/pages/events/tech/index.jsx
Labels: enhancement, gssoc23, level3

#293 Improved Font weight of Footer Right Section
  src/components/Footer.jsx
Labels: enhancement, gssoc23, level2

#303 feat(frontend): added spacing in FAQ section
  src/components/FaqAccordion.jsx
  src/components/header/index.js
Labels: enhancement, gssoc23, level2
