Repository devs-in-tech/DevsInTech, pull requests merged in 2023-05, with the labels that each got.

#99 Resolved the Margin Issues on the home page
  src/components/HomePage/aboutCommunity/index.jsx
Labels: enhancement, good first issue, GSSoC23, Level 1

#87 feat: add back to top button
  src/components/ScrollToTop.jsx
  src/pages/home/index.jsx
Labels: enhancement, good first issue, GSSoC23, under review, Level 2

#115 Added dynamic icons to the button component
  src/components/HeroSection/index.jsx
  src/components/button/index.js
Labels: GSSoC23, Level 2

#146 feat: add counter effect
  package.json
  pnpm-lock.yaml
  src/components/HomePage/stats/index.jsx
Labels: enhancement, good first issue, GSSoC23, Level 2

#135 feat: added hero text
  src/components/HeroSection/index.jsx
Labels: enhancement, good first issue, GSSoC23, Level 2

#140 feat: make navbar sticky
  src/components/Navbar.jsx
Labels: GSSoC23, Level 1

#148 readme badges added
  README.md
Labels: documentation, enhancement, GSSoC23, Level 1
