Repository devs-in-tech/DevsInTech, pull requests merged in 2023-08, with the labels that each got.

#447 Corrected Environment Variable for Alan AI API Key in Alan.js Componen
  src/pages/alan.js
Labels: gssoc23, level1

#311 feat(frontend): aligned font of the events page
  src/pages/events/index.jsx
Labels: enhancement, gssoc23, level2

#384 footer visibility resolve
  src/components/Footer.jsx
Labels: gssoc23, level2

#420 Error message shown below of subscribe section if empty field submit or invalid email entered
  src/components/Letter.jsx
Labels: enhancement, gssoc23, level2

#450 fix: Resolved Errors in feature-request.yml File and styles.yml File
  .github/ISSUE_TEMPLATE/feature-request.yml
  .github/ISSUE_TEMPLATE/style.yml
Labels: bug

#451 feat: Added Multiple workflows in GitHub Workflows Folder
  .github/workflows/close_old_issues.yml
  .github/workflows/issues.yml
  .github/workflows/lock.yml
  .github/workflows/prevent_multiple_issues.yml
Labels: enhancement
